default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: lkr_development
  pool: 5
  username: lkr
  password: 12345


test:
  adapter: postgresql
  encoding: unicode
  database: lkr_test
  pool: 5
  host: ''
  username: lkr
  password: 12345

production:
  <<: *default
  database: my_database_production