
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: lk_development
  pool: 5
  username: myapp
  password: password1


test:
  adapter: postgresql
  encoding: unicode
  database: lk_test
  pool: 5
  host: ''
  username: myapp
  password: password1

production:
  <<: *default
  database: my_database_production
